changelog:
  exclude:
    labels:
      - ci
      - style
      - testing
      - duplicate
      - invalid
      - wontfix
      - question
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - removal
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Performance
      labels:
        - performance
    - title: Dependencies
      labels:
        - dependencies
        - build
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - refactoring
        - github_actions
        - python
