default_config:

logger:
  default: info
  logs:
    aiocamedomotic: debug
    custom_components.came_domotic: debug
# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
