create_user:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: came_domotic
    username:
      required: true
      example: "newuser"
      selector:
        text:
    password:
      required: true
      example: "securepassword"
      selector:
        text:
    group:
      required: false
      default: "*"
      example: "ETI/Domo"
      selector:
        text:

delete_user:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: came_domotic
    username:
      required: true
      example: "olduser"
      selector:
        text:

change_password:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: came_domotic
    username:
      required: true
      example: "myuser"
      selector:
        text:
    current_password:
      required: true
      selector:
        text:
    new_password:
      required: true
      selector:
        text:

get_terminal_groups:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: came_domotic

get_users:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: came_domotic

force_refresh:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: came_domotic

set_timer_timetable:
  target:
    entity:
      integration: came_domotic
      domain: switch
  fields:
    days:
      required: false
      example: '["monday", "wednesday", "friday"]'
      selector:
        select:
          multiple: true
          options:
            - "monday"
            - "tuesday"
            - "wednesday"
            - "thursday"
            - "friday"
            - "saturday"
            - "sunday"
    slots:
      required: false
      example: '[{"start": "08:00", "stop": "12:00"}, {"start": "14:00", "stop": "18:00"}]'
      selector:
        object:
